- CHANGELOG.rst
- README.md
- docs/index.rst
- docs/reference/reference.rst
- docs/userguide/ohlc.rst
- energyquantified/api/__init__.py
- energyquantified/api/base.py
- energyquantified/api/ohlc.py
- energyquantified/base.py
- energyquantified/data/__init__.py
- energyquantified/data/base.py
- energyquantified/data/ohlc.py
- energyquantified/metadata/__init__.py
- energyquantified/metadata/ohlc.py
- energyquantified/parser/metadata.py
- energyquantified/parser/ohlc.py
- energyquantified/parser/timeseries.py
Closes #2.
**Adds OHLC support:**
- Add OHLC data and metadata classes
- Add parsers
- Add OHLC API
- Update documentation
> Add OHLC support

- CHANGELOG.rst
- docs/index.rst
- docs/intro/quickstart.rst
- docs/reference/reference.rst
- docs/userguide/instances.rst
- docs/userguide/ohlc.rst
- docs/userguide/pandas.rst
- docs/userguide/period-instances.rst
- docs/userguide/timeseries.rst
- energyquantified/data/base.py
- energyquantified/data/ohlc.py
- energyquantified/data/periodseries.py
- energyquantified/data/timeseries.py
- energyquantified/metadata/instance.py
- energyquantified/metadata/ohlc.py
- energyquantified/parser/periodseries.py
- energyquantified/parser/timeseries.py
- energyquantified/utils/__init__.py
- energyquantified/utils/lists.py
- energyquantified/utils/pandas.py
- examples/ohlc_download_and_plot.py
See #1.
**Features:**
**Documentation:**
> Improve pandas integrations

- energyquantified/metadata/area.py
Update the Python client with the latest area and border configuration:
* Add SEM
* Alegro cable (DE-BE)
* Update border statuses for multiple borders
> Update areas and borders

- CHANGELOG.rst
- README.md
- docs/index.rst
- docs/reference/packages.rst
- docs/reference/reference.rst
- docs/userguide/ohlc.rst
- docs/userguide/srmc.rst
- energyquantified/api/__init__.py
- energyquantified/api/base.py
- energyquantified/api/ohlc.py
- energyquantified/api/srmc.py
- energyquantified/base.py
- energyquantified/data/__init__.py
- energyquantified/data/ohlc.py
- energyquantified/data/srmc.py
- energyquantified/metadata/ohlc.py
- energyquantified/parser/metadata.py
- energyquantified/parser/srmc.py
> Add support for SRMC and OHLC-to-periods

- docs/index.rst
- docs/intro/quickstart-realto.rst
- docs/intro/quickstart.rst
- docs/reference/packages.rst
- docs/reference/reference.rst
- docs/userguide/auth.rst
- energyquantified/__init__.py
- energyquantified/api/__init__.py
- energyquantified/api/metadata.py
- energyquantified/base.py
Closes #24.
* Adds a way to connect to the Energy Quantified API for Realto users
* Add a chapter in the documentation for Realto integration
> Integrate with the API on Realto's marketplace

- docs/userguide/ohlc.rst
> Add documentation on the fill parameter

- CHANGELOG.rst
- docs/reference/reference.rst
- docs/userguide/metadata.rst
- energyquantified/api/metadata.py
* Add MetadataAPI.curve()
* Update documentation (both metadata userguide and the reference page)
> Add MetadataAPI.curve()

- .readthedocs.yaml
> Add readthedocs config file #75

- docs/userguide/periods.rst
- docs/userguide/terminology.rst
- docs/userguide/timeseries.rst
- energyquantified/api/instances.py
- energyquantified/api/ohlc.py
- energyquantified/api/period_instances.py
- energyquantified/api/periods.py
- energyquantified/api/srmc.py
- energyquantified/api/timeseries.py
- energyquantified/data/base.py
- energyquantified/data/ohlc.py
- energyquantified/data/periodseries.py
- energyquantified/data/srmc.py
- energyquantified/data/timeseries.py
- energyquantified/parser/ohlc.py
- energyquantified/parser/periodseries.py
- energyquantified/parser/srmc.py
- energyquantified/parser/timeseries.py
Please have a look at https://github.com/energyquantified/eq-python-client/issues/66#issuecomment-1525043630
Closes #66.
> Unit Parameter

- CHANGELOG.rst
- energyquantified/api/instances.py
Closes #81 and is part of energyquantified/core#235
> #81 Add `modified-at-latest` parameter to `eq.instances.relative()`

- CHANGELOG.rst
- docs/userguide/period-instances.rst
- energyquantified/api/period_instances.py
> #84 Add Relative Period Instances

- CHANGELOG.rst
- energyquantified/metadata/place.py
- energyquantified/parser/metadata.py
> #43 Remove Place.area

- CHANGELOG.rst
- energyquantified/api/instances.py
> #90 Remove limitation of parameters for relativ instances

- CHANGELOG.rst
- docs/reference/packages.rst
- docs/reference/reference.rst
- docs/userguide/instances.rst
- energyquantified/api/instances.py
- energyquantified/data/__init__.py
- energyquantified/data/absolute.py
- energyquantified/metadata/options.py
- energyquantified/parser/absolute.py
* Implement instances.absolute, closes #77, part of #83 
* Add documentation for absolute
* Add Aggregation.MEAN
* Change example in InstancesAPI docstring (from using eq.timeseries.load() to eq.instances.list())
> Implement absolute forecast for instances #77

- CHANGELOG.rst
- docs/userguide/metadata.rst
- energyquantified/api/base.py
- energyquantified/api/metadata.py
- examples/forecasts.py
- examples/search.py
- examples/timeseries.py
Added the option to filter curves on their curve type.
Closes #97.
> #97 Add filter option on curve type for curve search

- CHANGELOG.rst
- README.md
- docs/index.rst
- docs/intro/quickstart.rst
- docs/reference/packages.rst
- docs/reference/reference.rst
- docs/userguide/metadata.rst
- docs/userguide/ohlc.rst
- docs/userguide/periods.rst
- docs/userguide/srmc.rst
- docs/userguide/terminology.rst
- docs/userguide/timeseries.rst
- energyquantified/api/base.py
- energyquantified/metadata/__init__.py
- energyquantified/metadata/curve.py
- energyquantified/metadata/subscription.py
- energyquantified/parser/metadata.py
> #61 Add subscription information to curve

- energyquantified/parser/metadata.py
> #99 Use curve's timezone to parse created and modified of an instance

- CHANGELOG.rst
- docs/userguide/instances.rst
- energyquantified/api/instances.py
> Add rolling forecasts

- CHANGELOG.rst
- energyquantified/api/events.py
* Closes #104 
* Add log handlers in EventsAPI; stdout if level <= INFO, else stderr
> Remove call to logging.basicConfig #104 ++

- CHANGELOG.rst
- energyquantified/api/events.py
- energyquantified/http/session.py
* Add `User-Agent` header to push feed messages
> Modify the `User-Agent` header to be standard compliant +

- energyquantified/api/instances.py
https://github.com/energyquantified/eq-python-client/issues/122
> Fix typo in Instances.load

- CHANGELOG.rst
- energyquantified/api/instances.py
- energyquantified/api/period_instances.py
> Fix typo in method parameter

- CHANGELOG.rst
- energyquantified/data/base.py
- energyquantified/data/periodseries.py
* Fix `__iter__` and `__len__` for `Series`
* Add changelog item
> Bugfix Periodseries.to_timeseries()

- energyquantified/metadata/area.py
Kosovo is a price area, update the metadata definition.
Closes #146
> XK is price area
